feat: support statefulSets
arttor/helmify pull request #29
Opened 2022-02-25 10:22 UTC by Duologic

This PR implements support for StatefulSets, which is pretty much the same as Deployments.
To facilitate this I've abstracted out the processing of Deployment into logical functions
so that both the StatefulSet and Deployment can use them.

I've also hitched a small feature along with this change: templating Args into Values.

2022-03-13 10:50 UTC, arttor commented
@Duologic looks really nice! 
Can you please add statefulset sample to `test_data/sample-app.yaml`
And regenerate examples in /examples directory by running:
```shell
cat test_data/sample-app.yaml | go run ./cmd/helmify examples/app
```

2022-03-23 10:36 UTC, arttor requested changes

2022-03-23 10:36 UTC, arttor commented on pkg/processor/statefulset/statefulset.go
> +package statefulset
Please add statefulset sample to `test_data/sample-app.yaml`
And regenerate examples in /examples directory by running:

```shell
cat test_data/sample-app.yaml | go run ./cmd/helmify examples/app
```

2024-12-13 09:36 UTC, Duologic commented
Closing this as I have no intention to finish it, feel free to take any code from this PR and form a new one.

2024-12-13 09:36 UTC, closed without merging